Homework1
made-ml-in-prod-2021/kpotoh pull request #2
Opened 2021-05-03 13:23 UTC by KPOTOH

- Структура, как в примере, описание приведено в README. Код для процессинга модели, данных и фичей разнесен по модулям. Прогон пайплайна осуществляется в соответствующем файле. Эксперименты также лежат в отдельном файле (в README все видно). Пайплайн конфигурируется конфиг-файлами, для которых написаны датаклассы. EDA лежит в ноутбуке
- Кастомный трансформер признаков реализован
- Тесты покрывают значительную часть кода. Для тестов написан синтетический генератор данных, на основе исходных, лежит в `tests/global_fixtures.py`
- Удобный доступ к пайплайну осуществляется консольным интерфейсом (предсказание, тренировка)
- Для быстрого прогона предсказания в `models/` лежит одна модель и ее метрики
- В экспериментах участвовали логрег, лес и knn. Для каждой оставлен конфиг. Проверено, каким моделям лучше подходит скалинг числовых признаков. Гиперпараметры подобраны по сетке
- Логирование идет в файл (уровень debug) и поток ошибок (уровень info)
- Степень завершения домашнего задания изложена в README в виде таблицы и комментария.

2021-05-05 12:39 UTC, polikutinevgeny reviewed
Основные хайлайты:

- В экспериментах не хватает логгеров и конфигов
- Не сохраняется пайплайн, что чревато появлением новых, невиданных ранее фич в проде
- Есть ненужные комментарии там, где по коду и так понятно, что происходит
- Кастомный трансформер де-факто не нужен
- Не хватает конфига на predict
- Закоммичен .pkl файл модели, так делать не надо
- Не хватает параметров моделей в конфиге

Оценка:

Из 31 изначального балла я бы отнял: 

- 3 балла за трансформер, который в результате просто обёртка над ColumnTransformer
- 0.5 балла за отсутствие конфигов на predict
- И ещё 3 балла снял бы за то, что пайплайн не сохраняется, из-за чего predict де-факто весь работает некорректно.

Итого: 25.5 баллов (ух какой я злой)

А похвалил бы я за конфиг логирования в файле.

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/configs/train_config_trees.yml
> +    # - ""
Кажется, что это как закомменченный код: лучше так не делать

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/data/download_data.sh
> +mkdir ./data/raw -p
Возможно стоит использовать .gitkeep?

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/data/make_dataset.py
> +    """ split data to train and val parts """
Комментарий не имеет смысла: по сигнатуре функции и так понятно, что она делает

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/experiments.py
> +            fout.write(f"{mname}\t{best_params}\t{score}\n")
Кажется, что здесь стоит добавить logging

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/experiments.py
> +    warnings.filterwarnings('ignore')
Выключать все предупреждения - не лучшая идея, возможно имеет смысл выключить только те, которые мешают

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/experiments.py
> +TRAIN_CONFIG_PATH = "./configs/train_config_trees.yml"
Пути стоит принимать в качестве аргументов, а не хардкодить

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/features/build_features.py
> +    """ Смешать, но не взбалтывать """
Ну зачем?(

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/features/build_features.py
> +        return transformer
Зачем создавать класс-трансформер, который де-факто является обёрткой для других трансформеров? (понятно, что в задании было написано сделать трансформер, но кажется, что это совсем не то, что предполагалось сделать)

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/models/model_fit_predict.py
> +    return model
Параметры моделей захардкожены: не имеет ли смысла вынести их в конфигурацию?

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/models/model_fit_predict.py
> +def evaluate_model(predicts: np.ndarray, target: np.ndarray):
Стоит добавить аннотацию возвращаемого типа, для однообразия

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/models/model_fit_predict.py
> +    }
Возможно метрики тоже стоит вынести в конфигурацию

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/pipeline.py
> +DEFAULT_OUTPUT_PATH = './data/prediction.csv'
Стоит ли хардкодить дефолтные пути? Кажется, что это очень подверженная изменениям вещь, и стоит указывать её при каждом запуске.

Более того, путь к датасету/результатам стоит хранить в конфиге.

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/pipeline.py
> +    X = FeaturesExtractor(params.feature_params).fit_transform(df)
А вот так точно не стоит делать: ты де-факто заново обучаешь пайплайн на новых данных. Тебе стоило его сохранить после тренировки и потом загрузить.

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/pipeline.py
> +    logger.addHandler(handler)
Эта функция точно нужна? Она никогда не вызывается

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/ml_project/pipeline.py
> +    """main code to run script with console interface"""
Тоже комментарий, не несущий смысловой нагрузки

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/tests/data/test_make_data.py
> +from tests.global_fixtures import path_to_synthetic_data, synthetic_dataset
Если fixture определить в conftest.py, то их не надо импортировать

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/tests/features/test_features.py
> +    assert len(scaler.scale_) > 0, "scaler didn't fitted correctly"
test_fitting тестирует только Scaler? А что насчёт остальной начинки?

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/tests/features/test_features.py
> +    num_pipe = extractor_instance._transformer.named_transformers_['numerical_pipeline']
Кажется, что тестировать нужно только интерфейс, и стучаться к protected полям тут не очень хорошо

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/tests/model/test_train_models.py
> +    fitted_model.predict(X)
Стоит ещё проверить, а вернулось ли вообще хоть что-то

И вообще мне кажется, что надо код из fixture вынести сюда все же, так логичнее.

2021-05-05 12:39 UTC, polikutinevgeny commented on ml_project/tests/test_end2end_training.py
> +    )
А зачем пересоздавать конфиг, если на вход уже подаётся один

2021-05-06 11:57 UTC, Mikhail-M commented on ml_project/tests/data/test_make_data.py
> +from tests.global_fixtures import path_to_synthetic_data, synthetic_dataset
фикстуры импортировать ваще оч плохой тон, сделайте плз conftest и пропишете score
https://habr.com/ru/post/448786/

2021-05-06 11:59 UTC, Mikhail-M requested changes
пока что я согласен с оценкой и замечаниями коллеги. 
Баллы: 25.5

можно что-то поправить и позвать снова

@polikutinevgeny  отличное ревью

2021-05-09 22:00 UTC, KPOTOH commented
Дорабатывать не стал

2021-05-24 17:35 UTC, merged